### ISSUE TITLE
Question: how to handle pagination?

### ISSUE THREAD

**Issue by kettenbach-it** [bmeme/eventbrite_connector#3]
How do you handle  any kind of paginated result with this SDK?

**Comment by Fatal-Error** [comment]
Hi, you simply have to add the pagination conditions.
So, depending on the endpoint, you should add the `["continuation" => $continuation_token]` or the `["page" => $page_number]` to your `load()` function.

Eg:
`$eb->fetch('event')->load('search', ['continuation' => 'eyJwYWdlIjogMn0'])->getData()`
